# SonarQube project configuration
sonar.projectKey=DeepDhar75_SecurePipe
sonar.organization=deepdhar75
sonar.projectName=SecurePipe DevSecOps Pipeline
sonar.projectVersion=2.0.0

# Source & language
sonar.sources=app
sonar.language=py
sonar.python.version=3.11

# Test coverage
sonar.python.coverage.reportPaths=app/coverage.xml
sonar.python.xunit.reportPaths=app/test-results.xml

# Exclusions
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/tests/**,terraform/**